# Generated by Django 5.2.8 on 2025-11-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('academic_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.academicfee')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'academic_fee', 'receipt_number')},
            },
        ),
    ]
