# Generated by Django 5.2.8 on 2025-11-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_major', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentWeighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttype')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering')),
            ],
            options={
                'unique_together': {('course_offering', 'assessment_type')},
            },
        ),
    ]
