# Generated by Django 5.2.8 on 2025-11-18 14:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Année Académique', 'verbose_name_plural': 'Années Académiques'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculté', 'verbose_name_plural': 'Facultés'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semestre', 'verbose_name_plural': 'Semestres'},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2000, 7, 15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2000, 7, 15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
    ]
