# Generated by Django 5.2.8 on 2025-11-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(max_length=50)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering')),
            ],
        ),
    ]
