"""
Django settings for ums project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from a .env file (for SECRET_KEY, etc.)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production

# SECURITY WARNING: keep the secret key used in production secret!
# Fetches SECRET_KEY from environment variables, falling back to a secure default.
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-toi)&!&y*amk3ppl&v3w^b_@f=c=8bu_26+)y(tkud7f9cw)zw")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allows all hosts for development
ALLOWED_HOSTS = ["*"]


# ------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------
INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party (from reference)
    "rest_framework",
    "django_filters",
    "corsheaders",
    "drf_spectacular",
    "rest_framework_simplejwt",

    # UMS apps (from reference)
    "core",
    "students",
    "enrollment",
    "fees",
    "payments",
    "expenses",
    "courses",
    "staff",
    "assessments",
    "grades",
    "users",
]

# ------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'ums.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ums.wsgi.application'


# ------------------------------------------------------
# DATABASE (SQLite Configuration)
# ------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ------------------------------------------------------
# PASSWORDS / AUTH
# ------------------------------------------------------

# Sets the custom user model for authentication
AUTH_USER_MODEL = "users.User"

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------
LANGUAGE_CODE = 'en-us'

# Specific timezone for clarity
TIME_ZONE = 'Africa/Kinshasa'

USE_I18N = True

USE_TZ = True


# ------------------------------------------------------
# STATIC & MEDIA FILES
# ------------------------------------------------------
STATIC_URL = "/static/"
# Added STATIC_ROOT for collecting static files in production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Added MEDIA_URL and MEDIA_ROOT for user-uploaded files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# ------------------------------------------------------
# CORS CONFIG
# ------------------------------------------------------
# Allows all origins for development (be careful in production!)
CORS_ALLOW_ALL_ORIGINS = True


# ------------------------------------------------------
# REST FRAMEWORK CONFIG
# ------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


# ------------------------------------------------------
# JWT CONFIG
# ------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# ------------------------------------------------------
# SWAGGER / OPENAPI
# ------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "UMS API",
    "DESCRIPTION": "University Management System Microservice API",
    "VERSION": "1.0.0",
}


# ------------------------------------------------------
# DEFAULT PRIMARY KEY
# ------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'