# Generated by Django 5.2.8 on 2025-11-18 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('enrollment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondarychoice',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='secondarychoice',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment'),
        ),
        migrations.AddField(
            model_name='secondarychoice',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('enrollment', 'document_name')},
        ),
    ]
